# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

schedules:
- cron: '20 0 * * *'
  displayName: "Daily Automatioc Pipline Run"
  branches:
    include:
      - main
  always: true

pool:
  vmImage: ubuntu-latest

parameters:
  - name: SCRIPT_KEY_VAL
    displayName: 'Select script key'
    type: string
    default: 'test_demo'
    values:
      - test_demo_cr_hl
      - test_demo
      - test_demo_api
      - test_dev

steps:
- task: UseNode@1
  inputs:
    version: '20.x'

- script: |
    npm ci
  displayName: Install Dependencies

- script: |
    npx playwright install chromium
  displayName: Install Chromium

- script: |
    npm run ${{parameters.SCRIPT_KEY_VAL}}
  displayName: Run Tests

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'playwright-report'
    artifact: 'Playwright HTML Report'
    publishLocation: 'pipeline'
  condition: always()

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**test-results/junit-report.xml'
    testRunTitle: 'Playwright Junit Report'
  condition: always()